In [1]:
import numpy as np
import pandas as pd

In [13]:
np.__version__

'1.26.4'

In [14]:
pd.__version__

'2.2.2'

In [7]:
zeros_arr = np.zeros(5)
zeros_arr

array([0., 0., 0., 0., 0.])

In [11]:
zeros_arr.dtype

dtype('float64')

In [8]:
int_zeros=zeros_arr.astype(int)
int_zeros

array([0, 0, 0, 0, 0])

In [12]:
int_zeros.dtype

dtype('int32')

In [9]:
float_zeros=int_zeros.astype(float)
float_zeros

array([0., 0., 0., 0., 0.])

In [26]:
a=np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
a.shape

(4, 3)

In [29]:
b=np.random.randint(1,20,size=(4,3))

In [31]:
b

array([[ 7, 18, 16],
       [ 4, 16, 13],
       [15, 14, 11],
       [ 2, 10,  4]])

In [32]:
b.shape

(4, 3)

In [35]:
np.swapaxes(b,0,1)

array([[ 7,  4, 15,  2],
       [18, 16, 14, 10],
       [16, 13, 11,  4]])

In [36]:
np.max(b)

18

In [38]:
b.shape

(4, 3)

In [41]:
reshaped=b.reshape(3,4)

In [43]:
reshaped.shape

(3, 4)

In [ ]:
np.linspace(1,6,5, dtype="int")

array([1, 2, 3, 4, 6])

In [62]:
arr =np.array([1,65,75,89,24])
arr

array([ 1, 65, 75, 89, 24])

In [63]:
arr =np.array([[1,65,75,89,24],[5,64,8,6,9]])
np.sort(arr,axis=0)

array([[ 1, 64,  8,  6,  9],
       [ 5, 65, 75, 89, 24]])

In [64]:
np.sort(arr,axis=1)

array([[ 1, 24, 65, 75, 89],
       [ 5,  6,  8,  9, 64]])