In [47]:
import numpy as np
import pandas as pd

In [48]:
np.__version__

'1.26.4'

In [49]:
pd.__version__

'2.2.2'

In [50]:
zeros_arr = np.zeros(5)
zeros_arr

array([0., 0., 0., 0., 0.])

In [51]:
zeros_arr.dtype

dtype('float64')

In [52]:
int_zeros=zeros_arr.astype(int)
int_zeros

array([0, 0, 0, 0, 0])

In [53]:
int_zeros.dtype

dtype('int32')

In [54]:
float_zeros=int_zeros.astype(float)
float_zeros

array([0., 0., 0., 0., 0.])

In [55]:
a=np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
a.shape

(4, 3)

In [56]:
b=np.random.randint(1,20,size=(4,3))

In [57]:
b

array([[ 3, 16, 18],
       [ 7, 10, 10],
       [16, 19, 12],
       [12,  4,  5]])

In [58]:
b.shape

(4, 3)

In [59]:
np.swapaxes(b,0,1)

array([[ 3,  7, 16, 12],
       [16, 10, 19,  4],
       [18, 10, 12,  5]])

In [60]:
np.max(b)

19

In [61]:
b.shape

(4, 3)

In [62]:
reshaped=b.reshape(3,4)

In [63]:
reshaped.shape

(3, 4)

In [64]:
np.linspace(1,6,5, dtype="int")

array([1, 2, 3, 4, 6])

In [65]:
arr =np.array([1,65,75,89,24])
arr

array([ 1, 65, 75, 89, 24])

In [66]:
arr =np.array([[1,65,75,89,24],[5,64,8,6,9]])
np.sort(arr,axis=0)

array([[ 1, 64,  8,  6,  9],
       [ 5, 65, 75, 89, 24]])

In [67]:
np.sort(arr,axis=1)

array([[ 1, 24, 65, 75, 89],
       [ 5,  6,  8,  9, 64]])

In [68]:
?arr

Type:        ndarray
String form:
[[ 1 65 75 89 24]
 [ 5 64  8  6  9]]
Length:      2
File:        c:\users\tejas\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, o

In [69]:
array1 = np.array([1, 2, 3, "a"]) # This will create an array with dtype 'U21' (Unicode string) because of the presence of a string element
print(array1)
array1.dtype

['1' '2' '3' 'a']


dtype('<U11')

In [70]:
# Indexing
print("First Element: ",array1[0])
print(array1[-1])

First Element:  1
a


In [71]:
array1 = np.array([1.0, 2, 3]) # This will create an array with dtype 'float64' because all elements are numeric
print(array1)
array1.dtype

[1. 2. 3.]


dtype('float64')

In [72]:
array1[1] # Accessing the second element of the array

2.0

In [73]:
array1[-1] # Accessing the last element

3.0

In [74]:
array3=np.arange(2,11) # Creating an array with values from 2 to 10
array3

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
b = array3.reshape(3,3) # Reshaping the array to a 3x3 matrix   
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [76]:
x = np.array([[1,2,3],[2,3,4]]) # Creating a 2D array
y = np.array([[10,12,13],[12,13,14]]) 
print(x)
print(y)

[[1 2 3]
 [2 3 4]]
[[10 12 13]
 [12 13 14]]


In [77]:
z = x + y # Adding two arrays
print(z)

[[11 14 16]
 [14 16 18]]


In [78]:
import numpy as np
x = np.array([[1,2,3],[2,3,4]]) # Creating a 2D array
y = np.array([[10,12,13],[12,13,14]])
w = x * y # Element-wise multiplication of two arrays
print(w)

[[10 24 39]
 [24 39 56]]


In [79]:
array1 = np.array([1, 2, 3, 4, 5])
print(array1)

[1 2 3 4 5]


In [80]:
array1D = np.array([1,2,3,4,5]) # Creating a 1D array
array1D

array([1, 2, 3, 4, 5])

In [81]:
array2D = np.array([[1,2,3],[2,3,4]]) # Creating a 2D array
array2D

array([[1, 2, 3],
       [2, 3, 4]])

In [82]:
array3D = np.array([[1,2,3],[2,3,4],[3,4,5]]) # Creating a 3D array
array3D

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [83]:
?array1D # This will show the DocString for the array1D object, which includes information about its attributes and methods.

Object `array1D # This will show the DocString for the array1D object, which includes information about its attributes and methods.` not found.


In [84]:
array1 = np.array([10, 20, 5, 40, 30])

print(array1.argmax())  # Index of maximum value (40 → index 3)
print(array1.argmin())  # Index of minimum value (5 → index 2)

3
2


In [85]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])

In [86]:
# Addition
print(arr1 + arr2)   # [11 22 33]

# Subtraction
print(arr1 - arr2)   # [ 9 18 27]

# Multiplication
print(arr1 * arr2)   # [10 40 90]

# Division
print(arr1 / arr2)   # [10. 10. 10.]

# Power
print(arr1 ** 2)     # [100 400 900]

# Modulus
print(arr1 % arr2)   # [0 0 0]

# Combined (scalar + array)
print(arr1 + 5)      # [15 25 35]

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
[100 400 900]
[0 0 0]
[15 25 35]


In [87]:
arr = np.linspace(0, 10, 5) # Creating an array with 5 evenly spaced values between 0 and 10
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [88]:
arr = np.array([10, 15, 25, 40]) 
print(np.diff(arr)) # Calculating the difference between consecutive elements in the array

[ 5 10 15]
