In [1]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.26.4'

In [3]:
pd.__version__

'2.2.2'

In [4]:
zeros_arr = np.zeros(5)
zeros_arr

array([0., 0., 0., 0., 0.])

In [5]:
zeros_arr.dtype

dtype('float64')

In [6]:
int_zeros=zeros_arr.astype(int)
int_zeros

array([0, 0, 0, 0, 0])

In [7]:
int_zeros.dtype

dtype('int32')

In [8]:
float_zeros=int_zeros.astype(float)
float_zeros

array([0., 0., 0., 0., 0.])

In [9]:
a=np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
a.shape

(4, 3)

In [10]:
b=np.random.randint(1,20,size=(4,3))

In [11]:
b

array([[ 2, 15,  4],
       [12, 17, 14],
       [ 7, 19, 10],
       [10,  8,  1]])

In [12]:
b.shape

(4, 3)

In [13]:
np.swapaxes(b,0,1)

array([[ 2, 12,  7, 10],
       [15, 17, 19,  8],
       [ 4, 14, 10,  1]])

In [14]:
np.max(b)

19

In [15]:
b.shape

(4, 3)

In [16]:
reshaped=b.reshape(3,4)

In [17]:
reshaped.shape

(3, 4)

In [18]:
np.linspace(1,6,5, dtype="int")

array([1, 2, 3, 4, 6])

In [19]:
arr =np.array([1,65,75,89,24])
arr

array([ 1, 65, 75, 89, 24])

In [20]:
arr =np.array([[1,65,75,89,24],[5,64,8,6,9]])
np.sort(arr,axis=0)

array([[ 1, 64,  8,  6,  9],
       [ 5, 65, 75, 89, 24]])

In [21]:
np.sort(arr,axis=1)

array([[ 1, 24, 65, 75, 89],
       [ 5,  6,  8,  9, 64]])